#!/bin/bash
# ========================================
# FIX SCRIPT: REHome Page Brand Compliance
# ========================================
# Generated By: Agent Gamma (Surgical Editor)
# Target: REHome.jsx + RENav.jsx + REFooter.jsx
# Total Fixes: 11 violations
# Estimated Time: 5.5 minutes
# Expected Score Improvement: 76/100 → 95/100+
# ========================================

echo "==================================================================="
echo "   ZILLIO BRAND COMPLIANCE FIX SCRIPT - REHome Page"
echo "==================================================================="
echo ""
echo "Target Components:"
echo "  - REHome.jsx (4 violations)"
echo "  - RENav.jsx (3 violations)"
echo "  - REFooter.jsx (4 violations)"
echo ""
echo "Current Score: 76/100 (Grade B)"
echo "Expected Score: 95/100+ (Grade S)"
echo ""
echo "Total Violations: 11"
echo "  - HIGH: 1 violation"
echo "  - MEDIUM: 8 violations"
echo "  - LOW: 2 violations"
echo ""
echo "==================================================================="
echo ""

# Color codes for terminal
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
GOLD='\033[0;33m'
NC='\033[0m' # No Color

# ========================================
# PRIORITY 1: HIGH VIOLATIONS (1 fix)
# ========================================

echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${RED}  PRIORITY 1: HIGH SEVERITY VIOLATIONS${NC}"
echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# ========================================
# FIX #1: RENAV-001 (HIGH)
# ========================================
echo -e "${RED}[FIX #1] RENAV-001 - Navigation Height Inconsistency (HIGH)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Component: RENav.jsx"
echo "Line: 35"
echo "Severity: HIGH (-10 points)"
echo "Issue: Navigation bar height is 68px instead of standard 70px"
echo ""
echo "BEFORE:"
echo "  h-[68px]"
echo ""
echo "AFTER:"
echo "  h-[70px]"
echo ""
read -p "Apply this fix? (y/n): " response1
echo ""

# ========================================
# PRIORITY 2: MEDIUM VIOLATIONS (8 fixes)
# ========================================

echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}  PRIORITY 2: MEDIUM SEVERITY VIOLATIONS${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# ========================================
# FIX #2: REHOME-001 (MEDIUM)
# ========================================
echo -e "${YELLOW}[FIX #2] REHOME-001 - Properties Section Padding (MEDIUM)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Component: REHome.jsx"
echo "Line: 196"
echo "Severity: MEDIUM (-8 points)"
echo "Issue: Section padding py-20 md:py-28 instead of standard py-24 md:py-32"
echo ""
echo "BEFORE:"
echo "  <section className=\"py-20 md:py-28 bg-black text-white\">"
echo ""
echo "AFTER:"
echo "  <section className=\"py-24 md:py-32 bg-black text-white\">"
echo ""
read -p "Apply this fix? (y/n): " response2
echo ""

# ========================================
# FIX #3: REHOME-002 (MEDIUM)
# ========================================
echo -e "${YELLOW}[FIX #3] REHOME-002 - Services Section Padding (MEDIUM)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Component: REHome.jsx"
echo "Line: 240"
echo "Severity: MEDIUM (-8 points)"
echo "Issue: Section padding py-20 md:py-28 instead of standard py-24 md:py-32"
echo ""
echo "BEFORE:"
echo "  <section className=\"bg-white px-10 md:px-24 py-20 md:py-28\">"
echo ""
echo "AFTER:"
echo "  <section className=\"bg-white px-10 md:px-24 py-24 md:py-32\">"
echo ""
read -p "Apply this fix? (y/n): " response3
echo ""

# ========================================
# FIX #4: REHOME-003 (MEDIUM)
# ========================================
echo -e "${YELLOW}[FIX #4] REHOME-003 - Testimonials Section Padding (MEDIUM)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Component: REHome.jsx"
echo "Line: 266"
echo "Severity: MEDIUM (-6 points)"
echo "Issue: Section padding py-28 instead of standard py-24 or py-32"
echo ""
echo "BEFORE:"
echo "  <section className=\"relative overflow-hidden bg-black py-28\">"
echo ""
echo "AFTER:"
echo "  <section className=\"relative overflow-hidden bg-black py-32\">"
echo ""
read -p "Apply this fix? (y/n): " response4
echo ""

# ========================================
# FIX #5: RENAV-002 (MEDIUM)
# ========================================
echo -e "${YELLOW}[FIX #5] RENAV-002 - Navigation Horizontal Padding (MEDIUM)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Component: RENav.jsx"
echo "Line: 35"
echo "Severity: MEDIUM (-8 points)"
echo "Issue: Horizontal padding px-6 md:px-12 instead of standard px-8 md:px-16 lg:px-24"
echo ""
echo "BEFORE:"
echo "  <div className=\"flex items-center justify-between px-6 md:px-12 h-[68px]\">"
echo ""
echo "AFTER:"
echo "  <div className=\"flex items-center justify-between px-8 md:px-16 lg:px-24 h-[70px]\">"
echo ""
echo "Note: This fix combines with Fix #1 (height change)"
read -p "Apply this fix? (y/n): " response5
echo ""

# ========================================
# FIX #6: RENAV-003 (MEDIUM)
# ========================================
echo -e "${YELLOW}[FIX #6] RENAV-003 - Navigation Gap Spacing (MEDIUM)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Component: RENav.jsx"
echo "Line: 45"
echo "Severity: MEDIUM (-8 points)"
echo "Issue: Nav items gap-6 xl:gap-8 instead of standard gap-7 xl:gap-9"
echo ""
echo "BEFORE:"
echo "  <ul className=\"hidden lg:flex items-center gap-6 xl:gap-8\">"
echo ""
echo "AFTER:"
echo "  <ul className=\"hidden lg:flex items-center gap-7 xl:gap-9\">"
echo ""
read -p "Apply this fix? (y/n): " response6
echo ""

# ========================================
# FIX #7: REFOOTER-001 (MEDIUM)
# ========================================
echo -e "${YELLOW}[FIX #7] REFOOTER-001 - Footer Background Color (MEDIUM)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Component: REFooter.jsx"
echo "Line: 15"
echo "Severity: MEDIUM (-7 points)"
echo "Issue: Footer background #0a0a0a instead of preferred #000000 or #050505"
echo ""
echo "BEFORE:"
echo "  <footer style={{ background: \"#0a0a0a\" }} className=\"text-white border-t border-white/5\">"
echo ""
echo "AFTER:"
echo "  <footer style={{ background: \"#000000\" }} className=\"text-white border-t border-white/10\">"
echo ""
echo "Note: This also fixes border-white/5 → border-white/10 (REFOOTER-004)"
read -p "Apply this fix? (y/n): " response7
echo ""

# ========================================
# FIX #8: REFOOTER-002 (MEDIUM)
# ========================================
echo -e "${YELLOW}[FIX #8] REFOOTER-002 - Footer Horizontal Padding (MEDIUM)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Component: REFooter.jsx"
echo "Line: 21"
echo "Severity: MEDIUM (-6 points)"
echo "Issue: Footer padding px-8 md:px-16 lg:px-24 instead of standard px-8 md:px-20"
echo ""
echo "BEFORE:"
echo "  <div className=\"relative px-8 md:px-16 lg:px-24 pt-16 pb-20 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-10\">"
echo ""
echo "AFTER:"
echo "  <div className=\"relative px-8 md:px-20 py-16 md:py-20 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-10\">"
echo ""
echo "Note: This also fixes asymmetric padding pt-16 pb-20 → py-16 md:py-20 (REFOOTER-003)"
read -p "Apply this fix? (y/n): " response8
echo ""

# ========================================
# FIX #9: REFOOTER-003 (MEDIUM)
# ========================================
echo -e "${YELLOW}[FIX #9] REFOOTER-003 - Footer Vertical Padding (MEDIUM)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Component: REFooter.jsx"
echo "Line: 21"
echo "Severity: MEDIUM (-6 points)"
echo "Issue: Asymmetric padding pt-16 pb-20 instead of symmetric py-16 md:py-20"
echo ""
echo "Status: COMBINED WITH FIX #8"
echo "This violation is fixed as part of the comprehensive padding update in Fix #8"
echo ""

# ========================================
# PRIORITY 3: LOW VIOLATIONS (2 fixes)
# ========================================

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}  PRIORITY 3: LOW SEVERITY VIOLATIONS${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# ========================================
# FIX #10: REHOME-004 (LOW)
# ========================================
echo -e "${BLUE}[FIX #10] REHOME-004 - Border Opacity Non-Standard (LOW)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Component: REHome.jsx"
echo "Line: 136"
echo "Severity: LOW (-2 points)"
echo "Issue: Border opacity rgba(0,0,0,0.07) instead of standard rgba(0,0,0,0.05) or 0.10"
echo ""
echo "BEFORE:"
echo "  style={{ borderColor: \"rgba(0,0,0,0.07)\" }}"
echo ""
echo "AFTER:"
echo "  style={{ borderColor: \"rgba(0,0,0,0.05)\" }}"
echo ""
read -p "Apply this fix? (y/n): " response10
echo ""

# ========================================
# FIX #11: REFOOTER-004 (LOW)
# ========================================
echo -e "${BLUE}[FIX #11] REFOOTER-004 - Footer Border Opacity (LOW)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Component: REFooter.jsx"
echo "Line: 15"
echo "Severity: LOW (-3 points)"
echo "Issue: Footer border border-white/5 instead of standard border-white/10"
echo ""
echo "Status: COMBINED WITH FIX #7"
echo "This violation is fixed as part of the footer background update in Fix #7"
echo ""

# ========================================
# EXECUTION SUMMARY
# ========================================

echo ""
echo "==================================================================="
echo "   FIX EXECUTION SUMMARY"
echo "==================================================================="
echo ""

total_applied=0
if [ "$response1" = "y" ]; then ((total_applied++)); fi
if [ "$response2" = "y" ]; then ((total_applied++)); fi
if [ "$response3" = "y" ]; then ((total_applied++)); fi
if [ "$response4" = "y" ]; then ((total_applied++)); fi
if [ "$response5" = "y" ]; then ((total_applied++)); fi
if [ "$response6" = "y" ]; then ((total_applied++)); fi
if [ "$response7" = "y" ]; then ((total_applied++)); fi
if [ "$response8" = "y" ]; then ((total_applied++)); fi
if [ "$response10" = "y" ]; then ((total_applied++)); fi

echo "Fixes Selected: $total_applied / 9 (2 fixes combined with others)"
echo "Total Violations Resolved: 11"
echo ""
echo "Files to Modify:"
echo "  - REHome.jsx: 4 violations"
echo "  - RENav.jsx: 3 violations"
echo "  - REFooter.jsx: 4 violations"
echo ""
echo "Expected Score Improvement:"
echo "  Current: 76/100 (Grade B)"
echo "  After Fixes: 95+/100 (Grade S)"
echo "  Point Gain: +19 points minimum"
echo ""
echo "Next Steps:"
echo "  1. Review the Edit commands below"
echo "  2. Apply fixes using Claude Code Edit tool"
echo "  3. Re-run Agent Beta v2.0 audit to verify score"
echo "  4. Confirm score reaches 95/100+"
echo ""
echo "==================================================================="
echo ""

# ========================================
# EDIT COMMANDS FOR CLAUDE CODE
# ========================================

echo "==================================================================="
echo "   EXACT EDIT COMMANDS (Copy & Execute in Claude Code)"
echo "==================================================================="
echo ""
echo "Use these Edit commands in Claude Code to apply fixes:"
echo ""

# Fix #1: Navigation height
if [ "$response1" = "y" ]; then
  echo "# Fix #1: RENAV-001 (Navigation Height)"
  echo "Edit("
  echo "  file_path=\"/Users/lgzlholding/Documents/dev-website Templates_cloning from ai/Projects/004 Zillio/neom-vision-template/src/components/realestate/RENav.jsx\","
  echo "  old_string=\"<div className=\\\"flex items-center justify-between px-6 md:px-12 h-[68px]\\\">\","
  echo "  new_string=\"<div className=\\\"flex items-center justify-between px-8 md:px-16 lg:px-24 h-[70px]\\\">\""
  echo ")"
  echo ""
fi

# Fix #2: Properties section padding
if [ "$response2" = "y" ]; then
  echo "# Fix #2: REHOME-001 (Properties Section Padding)"
  echo "Edit("
  echo "  file_path=\"/Users/lgzlholding/Documents/dev-website Templates_cloning from ai/Projects/004 Zillio/neom-vision-template/src/pages/REHome.jsx\","
  echo "  old_string=\"<section className=\\\"py-20 md:py-28 bg-black text-white\\\">\","
  echo "  new_string=\"<section className=\\\"py-24 md:py-32 bg-black text-white\\\">\""
  echo ")"
  echo ""
fi

# Fix #3: Services section padding
if [ "$response3" = "y" ]; then
  echo "# Fix #3: REHOME-002 (Services Section Padding)"
  echo "Edit("
  echo "  file_path=\"/Users/lgzlholding/Documents/dev-website Templates_cloning from ai/Projects/004 Zillio/neom-vision-template/src/pages/REHome.jsx\","
  echo "  old_string=\"<section className=\\\"bg-white px-10 md:px-24 py-20 md:py-28\\\">\","
  echo "  new_string=\"<section className=\\\"bg-white px-10 md:px-24 py-24 md:py-32\\\">\""
  echo ")"
  echo ""
fi

# Fix #4: Testimonials section padding
if [ "$response4" = "y" ]; then
  echo "# Fix #4: REHOME-003 (Testimonials Section Padding)"
  echo "Edit("
  echo "  file_path=\"/Users/lgzlholding/Documents/dev-website Templates_cloning from ai/Projects/004 Zillio/neom-vision-template/src/pages/REHome.jsx\","
  echo "  old_string=\"<section className=\\\"relative overflow-hidden bg-black py-28\\\">\","
  echo "  new_string=\"<section className=\\\"relative overflow-hidden bg-black py-32\\\">\""
  echo ")"
  echo ""
fi

# Fix #6: Nav gap spacing
if [ "$response6" = "y" ]; then
  echo "# Fix #6: RENAV-003 (Navigation Gap Spacing)"
  echo "Edit("
  echo "  file_path=\"/Users/lgzlholding/Documents/dev-website Templates_cloning from ai/Projects/004 Zillio/neom-vision-template/src/components/realestate/RENav.jsx\","
  echo "  old_string=\"<ul className=\\\"hidden lg:flex items-center gap-6 xl:gap-8\\\">\","
  echo "  new_string=\"<ul className=\\\"hidden lg:flex items-center gap-7 xl:gap-9\\\">\""
  echo ")"
  echo ""
fi

# Fix #7: Footer background + border
if [ "$response7" = "y" ]; then
  echo "# Fix #7: REFOOTER-001 + REFOOTER-004 (Footer Background + Border)"
  echo "Edit("
  echo "  file_path=\"/Users/lgzlholding/Documents/dev-website Templates_cloning from ai/Projects/004 Zillio/neom-vision-template/src/components/realestate/REFooter.jsx\","
  echo "  old_string=\"<footer style={{ background: \\\"#0a0a0a\\\" }} className=\\\"text-white border-t border-white/5\\\">\","
  echo "  new_string=\"<footer style={{ background: \\\"#000000\\\" }} className=\\\"text-white border-t border-white/10\\\">\""
  echo ")"
  echo ""
fi

# Fix #8: Footer padding (horizontal + vertical combined)
if [ "$response8" = "y" ]; then
  echo "# Fix #8: REFOOTER-002 + REFOOTER-003 (Footer Padding)"
  echo "Edit("
  echo "  file_path=\"/Users/lgzlholding/Documents/dev-website Templates_cloning from ai/Projects/004 Zillio/neom-vision-template/src/components/realestate/REFooter.jsx\","
  echo "  old_string=\"<div className=\\\"relative px-8 md:px-16 lg:px-24 pt-16 pb-20 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-10\\\">\","
  echo "  new_string=\"<div className=\\\"relative px-8 md:px-20 py-16 md:py-20 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-10\\\">\""
  echo ")"
  echo ""
fi

# Fix #10: Border opacity
if [ "$response10" = "y" ]; then
  echo "# Fix #10: REHOME-004 (Border Opacity)"
  echo "Edit("
  echo "  file_path=\"/Users/lgzlholding/Documents/dev-website Templates_cloning from ai/Projects/004 Zillio/neom-vision-template/src/pages/REHome.jsx\","
  echo "  old_string=\"style={{ borderColor: \\\"rgba(0,0,0,0.07)\\\" }}\","
  echo "  new_string=\"style={{ borderColor: \\\"rgba(0,0,0,0.05)\\\" }}\""
  echo ")"
  echo ""
fi

echo ""
echo "==================================================================="
echo "   VERIFICATION PROTOCOL"
echo "==================================================================="
echo ""
echo "After applying fixes:"
echo ""
echo "1. Run audit verification:"
echo "   Claude Code: 'Re-audit REHome page with Agent Beta v2.0'"
echo ""
echo "2. Expected results:"
echo "   - Score: 95/100+ (Grade S)"
echo "   - Violations: 0 catastrophic, 0 critical, 0 high"
echo "   - Remaining issues: 0-1 low severity (acceptable)"
echo ""
echo "3. If score < 95/100:"
echo "   - Review audit_report_REHome.yaml for remaining issues"
echo "   - Generate new fix script for any remaining violations"
echo ""
echo "==================================================================="
echo ""
echo -e "${GREEN}Fix script complete. Ready for execution!${NC}"
echo ""
